version: '3.7'
services:
  database:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=workshop
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
volumes:
  data:
